<a href="https://colab.research.google.com/github/q10l01p/deep-learning/blob/main/%E7%AC%AC%E4%BA%8C%E7%AB%A0_PyTorch%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1 PyTorch安装

# 2.2 张量


*   标量：一个单独的数
*   向量：一行或一列的数组
*   矩阵：一个二维数组
*   张量：数组维数超过二维

在PyTorch中，张量可以是标量，向量，矩阵

## 2.2.1 张量数据类型

torch默认的数据类型是32位浮点型，可以通过```torch.set_default_tensor_type()```函数进行修改，但只支持浮点型。



In [2]:
import torch
torch.tensor([1.2, 3.4]).dtype
# torch.tensor（）生成一个张量 .dtype获取张量数据类型

torch.float32

In [ ]:
# torch.set_default_tensor_type（）修改张量默认数据类型
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float64

In [ ]:
#其他数据转换方式
a = torch.tensor([1.2, 3.4])
print("a.dtype:",a.dtype)
print("a.long()方法:",a.long().dtype)
print("a.int()方法:",a.int().dtype)
print("a.float()方法:",a.float().dtype)

a.dtype: torch.float64
a.long()方法: torch.int64
a.int()方法: torch.int32
a.float()方法: torch.float32


In [ ]:
torch.set_default_tensor_type(torch.FloatTensor)
torch.get_default_dtype()
# torch.get_default_dtype()读取张量数据类型

torch.float32

总结：
1.   torch默认数据类型为torch.float32
2.   ```torch.set_default_tensor_type()```函数可以修改默认数据类型，但只支持浮点型。
3.   ```.dtype```，```torch.get_default_dtype()```函数可以读取张量数据类型
4.   ```.long()```,```.int()```,```.float()```也可以转换数据类型

## 2.2.2 张量的生成

### ```torch.tensor()``` 函数生成张量



In [ ]:
A = torch.tensor([[1.0,1.0],[2,2]])
A

tensor([[1., 1.],
        [2., 2.]])

```.shape```查看张量的维度

```.size()```查看张量的现状大小

```.numel()```查看张量包含的数量

In [ ]:
print(A.shape)
print(A.size())
print(A.numel())

torch.Size([2, 2])
torch.Size([2, 2])
4


同时可以使用参数dtype来指定张量的数据类型，使用传输requires_grad来指定张量是否需要计算梯度。

只有计算了梯度的张量，才能在深度学习优化时根据梯度大小进行更新。

In [ ]:
B = torch.tensor((1,2,3), dtype = torch.float32,requires_grad = True)
B

tensor([1., 2., 3.], requires_grad=True)

只有浮点型才能计算梯度

In [ ]:
# 计算sum（B**2）的梯度
Y = B.pow(2).sum()
Y.backward()     # Y.backward()函数是计算梯度的函数
B.grad        # B.grad存储了Y相对于B的梯度

tensor([2., 4., 6.])

### torch.Tensor()函数

```torch.Tensor()```函数可以生成张量，而且可以生成指定形状的张量。

In [3]:
C = torch.Tensor([1,2,3,4])
C

tensor([1., 2., 3., 4.])

In [4]:
D = torch.Tensor(2,3)
D

tensor([[6.3030e+30, 4.5703e-41, 8.6300e-35],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])

```torch.***_like()```可以生成与指定张量维度相同，性质相似的张量。

In [13]:
print(torch.ones_like(D)) # ones 全为1
print(torch.zeros_like(D)) 
print(torch.rand_like(D))
print(torch.empty_like(D))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0723, 0.8451, 0.1794],
        [0.3301, 0.0828, 0.1425]])
tensor([[2.3964e-34, 0.0000e+00, 6.3030e+30],
        [4.5703e-41, 4.4842e-44, 0.0000e+00]])


```.new_tensor()```函数可以创建新的张量。

In [14]:
# 创建一个类型相似但尺寸不同的张量
E = [[1,2],[3,4]]
E = D.new_tensor(E)
print("D:",D)
print("D.dtype:",D.dtype)
print("E:",E)
print("E.dtype:",E.dtype)

D: tensor([[6.3030e+30, 4.5703e-41, 8.6300e-35],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
D.dtype: torch.float32
E: tensor([[1., 2.],
        [3., 4.]])
E.dtype: torch.float32


* ```D.new_full((3,3), fill_value = 1)``` 生成3*3使用1填充的张量
* ```D.new_zeros((3,3))```          生成3*3使用0填充的张量
* ```D.new_empty((3,3))```          生成3*3使用空张量
* ```D.new_ones((3,3))```          生成3*3使用1填充的张量

### 张量和NumPy数据转换

NumPy数组默认的是64位浮点型

In [16]:
# 利用NumPy数组生成张量
import numpy as np
F = np.ones((3,3))
# 使用torch.as_tensor()函数
Ftensor = torch.as_tensor(F)
print(Ftensor)
# 使用torch.from_numpy()函数
Ftensor = torch.from_numpy(F)
print(Ftensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


```torch.as_tensor()```,```torch.from_numpy()```不改变数据类型



In [17]:
# 张量转换为NumPy数组
Ftensor.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 随机数生成张量

在PyTorch中可以通过相关随机数来生成张量，并且指定生成随机数的分布函数等。

在生成随机数之前可以通过```torch.manual_seed()```函数，指定随机数种子，用于保证随机数可以重复出现

随机数种子：可以通过改变随机数种子改变随机数

In [51]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0,std = torch.tensor(1.0))
A

tensor(-0.1115)

```torch.normal(mean = 0.0,std = torch.tensor(1.0))```函数中通过mean参数指定随机数的均值，通过std参数指定随机数的标准差

如果mean参数和std参数只有一个值，则可生成一个随机数

如果mean参数和std参数有多个值，则可生成多个随机数

In [29]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0, std=torch.arange(1,5.0))
A

tensor([-0.1115,  0.2407, -1.1089, -0.9617])

In [30]:
torch.manual_seed(123)
A = torch.normal(mean = torch.arange(1,5.0),std=torch.arange(1,5.0))
A

tensor([0.8885, 2.2407, 1.8911, 3.0383])

In [32]:
torch.manual_seed(123)
B = torch.rand(3,4)
B

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

In [33]:
torch.manual_seed(123)
C = torch.ones(2,3)
D = torch.rand_like(C)
D

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [34]:
print(torch.randn(3,3))
print(torch.randn_like(C))

tensor([[ 0.9447,  0.6217, -1.3501],
        [-0.1881, -2.3891, -0.4759],
        [ 1.7603,  0.6547,  0.5490]])
tensor([[ 0.3671,  0.1219,  0.6466],
        [-1.4168,  0.8429, -0.6307]])


```.randperm(n)```在0~n（包含0，不包含n）之间的整数进行随机排序后输出

In [35]:
torch.manual_seed(123)
torch.randperm(10)

tensor([2, 0, 8, 1, 3, 7, 4, 9, 5, 6])

### 其他生成张量的函数

In [36]:
torch.arange(start=0, end=10, step=2)
#start指定开始 end指定结束 step指定步长

tensor([0, 2, 4, 6, 8])

```torch.linspace(start=0.1, end=10, steps=5)```在范围内生成固定数量的等间隔张量

In [53]:
torch.linspace(start=0.1, end=10, steps=5)

tensor([ 0.1000,  2.5750,  5.0500,  7.5250, 10.0000])

```torch.logspace```生成以对数为间隔的张量。

```torch.logspace(start=0.1, end=1, steps=5)``` = 10**```torch.linspace(start=0.1, end=10, steps=5)```

In [54]:
torch.logspace(start=0.1, end=1, steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [55]:
print(torch.zeros(3,3))
print(torch.ones(3,3))
print(torch.eye(3))
print(torch.empty(3,3))
print(torch.full((3,3),fill_value = 0.25))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[2.3920e-34, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.1210e-43]])
tensor([[0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500]])


## 2.2.3 张量操作