<a href="https://colab.research.google.com/github/q10l01p/deep-learning/blob/main/%E7%AC%AC%E4%BA%8C%E7%AB%A0_PyTorch%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1 PyTorch安装

# 2.2 张量


*   标量：一个单独的数
*   向量：一行或一列的数组
*   矩阵：一个二维数组
*   张量：数组维数超过二维

在PyTorch中，张量可以是标量，向量，矩阵

## 2.2.1 张量数据类型

torch默认的数据类型是32位浮点型，可以通过```torch.set_default_tensor_type()```函数进行修改，但只支持浮点型。



In [ ]:
import torch
torch.tensor([1.2, 3.4]).dtype
# torch.tensor（）生成一个张量 .dtype获取张量数据类型

torch.float32

In [2]:
# torch.set_default_tensor_type（）修改张量默认数据类型
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float64

In [4]:
#其他数据转换方式
a = torch.tensor([1.2, 3.4])
print("a.dtype:",a.dtype)
print("a.long()方法:",a.long().dtype)
print("a.int()方法:",a.int().dtype)
print("a.float()方法:",a.float().dtype)

a.dtype: torch.float64
a.long()方法: torch.int64
a.int()方法: torch.int32
a.float()方法: torch.float32


In [6]:
torch.set_default_tensor_type(torch.FloatTensor)
torch.get_default_dtype()
# torch.get_default_dtype()读取张量数据类型

torch.float32

总结：
1.   torch默认数据类型为torch.float32
2.   ```torch.set_default_tensor_type()```函数可以修改默认数据类型，但只支持浮点型。
3.   ```.dtype```，```torch.get_default_dtype()```函数可以读取张量数据类型
4.   ```.long()```,```.int()```,```.float()```也可以转换数据类型

## 2.2.2 张量的生成

### ```torch.tensor()``` 函数生成张量



In [8]:
A = torch.tensor([[1.0,1.0],[2,2]])
A

tensor([[1., 1.],
        [2., 2.]])

```.shape```查看张量的维度

```.size()```查看张量的现状大小

```.numel()```查看张量包含的数量

In [10]:
print(A.shape)
print(A.size())
print(A.numel())

torch.Size([2, 2])
torch.Size([2, 2])
4


同时可以使用参数dtype来指定张量的数据类型，使用传输requires_grad来指定张量是否需要计算梯度。

只有计算了梯度的张量，才能在深度学习优化时根据梯度大小进行更新。

In [14]:
B = torch.tensor((1,2,3), dtype = torch.float32,requires_grad = True)
B

tensor([1., 2., 3.], requires_grad=True)

只有浮点型才能计算梯度

In [15]:
# 计算sum（B**2）的梯度
Y = B.pow(2).sum()
Y.backward()     # Y.backward()函数是计算梯度的函数
B.grad        # B.grad存储了Y相对于B的梯度

tensor([2., 4., 6.])